-- This file is generated by locale.py.
local L = LibStub("AceLocale-3.0"):NewLocale("XPBarNone", "enUS", true)
if not L then return end
--
-- File: XPBarNone/Core.lua
-- In function: GetOptions
L["Lock"] = true
L["Toggle the locking."] = true
L["Screen Clamp"] = true
L["Toggle screen clamping."] = true
L["Commify"] = true
L["Insert thousands separators into long numbers."] = true
L["Border"] = true
L["Toggle the border."] = true
L["Bubbles"] = true
L["Toggle bubbles on the XP bar."] = true
L["Scale"] = true
L["Set the bar scale."] = true
L["Width"] = true
L["Set the bar width."] = true
L["Height"] = true
L["Set the bar height."] = true
L["Font"] = true
L["Set the font."] = true
L["Font Size"] = true
L["Change the size of the text."] = true
L["Font Outline"] = true
L["Toggles the font outline."] = true
L["Text Position"] = true
L["Select the position of the text on XPBarNone."] = true
L["Mouse Over"] = true
L["Toggles switching between XP bar and Rep bar when you mouse over XPBarNone."] = true
L["Frame Strata"] = true
L["Set the frame strata."] = true
L["Texture"] = true
L["Set the bar texture."] = true
L["Hide Text"] = true
L["Hide the text on the XP and Rep bars."] = true
L["Show Zero"] = true
L["Show zero values in the various Need tags, instead of an empty string"] = true
L["Dynamic Bars"] = true
L["Show Rep bar on max level, XP bar on lower levels."] = true
L["Experience"] = true
L["Experience Bar related options"] = true
L["Customise Text"] = true
L["Customise the XP text string."] = true
L["Remaining Rested XP"] = true
L["Toggle the display of remaining rested XP."] = true
L["Rest Indication"] = true
L["Toggle the rest indication."] = true
L["Reputation Bar"] = true
L["Reputation Bar related options"] = true
L["Customise the Reputation text string."] = true
L["Auto Watch Reputation"] = true
L["Automatically watch the factions you gain rep with."] = true
L["Show Reputation"] = true
L["Show the reputation bar instead of the XP bar."] = true
L["Bar Colours"] = true
L["Set the colours for various XPBarNone bars."] = true
L["Normal"] = true
L["Set the colour of the normal bar."] = true
L["Rested"] = true
L["Set the colour of the rested bar."] = true
L["Resting"] = true
L["Set the colour of the resting bar."] = true
L["Remaining"] = true
L["Set the colour of the remaining bar."] = true
L["Set the colour of the Exalted reputation bar."] = true
L["Reputation Menu"] = true
L["Configure the reputation menu."] = true
L["Set the scale of the reputation menu."] = true
L["Auto Hide Delay"] = true
L["Set the length of time (in seconds) it takes for the menu to disappear once you move the mouse away."] = true
-- In function: XPBarNone:OnInitialize
L["XP Bar"] = true
L["Profiles"] = true
-- In function: GetRepTooltipText
L["Standing: %s\nRep: %s/%s [%.1f%%]"] = true
-- In function: XPBarNone:UpdateRepData
L["You need to select a faction to watch."] = true
-- In function: XPBarNone:DrawRepMenu
L["Click to expand %s faction listing"] = true
L["Click to collapse %s faction listing"] = true
L["Right click to watch faction"] = true
